//! Directory resolution abstraction for platform-specific paths.
//!
//! This module provides a trait-based abstraction over directory resolution,
//! enabling dependency injection for testing. The [`BaseDirs`] trait defines
//! the interface for resolving platform-specific directories, while
//! [`SystemBaseDirs`] provides the real implementation using the `dirs` crate.
//!
//! # Testing
//!
//! In tests, use `MockBaseDirs` (generated by mockall) to avoid writing to
//! the user's actual home directory.

use std::path::PathBuf;

/// Abstraction for resolving platform-specific base directories.
///
/// This trait enables dependency injection for directory resolution,
/// allowing tests to use mock implementations that don't touch the
/// real filesystem.
///
/// # Examples
///
/// ```no_run
/// use whitaker_installer::dirs::{BaseDirs, SystemBaseDirs};
///
/// let dirs = SystemBaseDirs;
/// if let Some(bin_dir) = dirs.bin_dir() {
///     println!("Executables go in: {}", bin_dir.display());
/// }
/// ```
#[cfg_attr(test, mockall::automock)]
pub trait BaseDirs {
    /// Returns the user's home directory.
    ///
    /// - Unix: `$HOME` or `/home/<user>`
    /// - Windows: `%USERPROFILE%` or `C:\Users\<user>`
    fn home_dir(&self) -> Option<PathBuf>;

    /// Returns the platform-specific data directory.
    ///
    /// - Linux: `~/.local/share`
    /// - macOS: `~/Library/Application Support`
    /// - Windows: `%LOCALAPPDATA%`
    fn data_dir(&self) -> Option<PathBuf>;

    /// Returns the platform-specific local data directory.
    ///
    /// On most platforms this is the same as `data_dir()`, but on Windows
    /// this specifically returns `%LOCALAPPDATA%`.
    fn data_local_dir(&self) -> Option<PathBuf>;

    /// Returns the directory for user executables.
    ///
    /// - Unix: `~/.local/bin`
    /// - Windows: `%LOCALAPPDATA%\whitaker\bin`
    fn bin_dir(&self) -> Option<PathBuf> {
        #[cfg(unix)]
        {
            self.home_dir().map(|h| h.join(".local").join("bin"))
        }
        #[cfg(windows)]
        {
            self.data_local_dir()
                .map(|d| d.join("whitaker").join("bin"))
        }
        #[cfg(not(any(unix, windows)))]
        {
            None
        }
    }

    /// Returns the directory for cloning the Whitaker repository.
    ///
    /// This is `<data_dir>/whitaker` on all platforms.
    fn whitaker_data_dir(&self) -> Option<PathBuf> {
        self.data_dir().map(|d| d.join("whitaker"))
    }
}

/// Real implementation of [`BaseDirs`] using the `dirs` crate.
///
/// This implementation resolves actual platform-specific directories
/// and should be used in production code.
///
/// # Examples
///
/// ```no_run
/// use whitaker_installer::dirs::{BaseDirs, SystemBaseDirs};
///
/// let dirs = SystemBaseDirs;
/// let data_dir = dirs.whitaker_data_dir()
///     .expect("could not determine data directory");
/// println!("Whitaker data at: {}", data_dir.display());
/// ```
#[derive(Debug, Clone, Copy, Default)]
pub struct SystemBaseDirs;

impl BaseDirs for SystemBaseDirs {
    fn home_dir(&self) -> Option<PathBuf> {
        dirs::home_dir()
    }

    fn data_dir(&self) -> Option<PathBuf> {
        dirs::data_dir()
    }

    fn data_local_dir(&self) -> Option<PathBuf> {
        dirs::data_local_dir()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn system_base_dirs_returns_some_on_supported_platforms() {
        let dirs = SystemBaseDirs;

        // These should return Some on Linux, macOS, and Windows
        assert!(
            dirs.home_dir().is_some(),
            "expected home_dir to return Some"
        );
        assert!(
            dirs.data_dir().is_some(),
            "expected data_dir to return Some"
        );
        assert!(
            dirs.data_local_dir().is_some(),
            "expected data_local_dir to return Some"
        );
    }

    #[test]
    fn whitaker_data_dir_contains_whitaker() {
        let dirs = SystemBaseDirs;
        let data_dir = dirs.whitaker_data_dir();

        assert!(
            data_dir.is_some(),
            "expected whitaker_data_dir to return Some"
        );
        assert!(
            data_dir
                .as_ref()
                .is_some_and(|p| p.to_string_lossy().contains("whitaker")),
            "expected path to contain 'whitaker'"
        );
    }

    #[cfg(unix)]
    #[test]
    fn bin_dir_is_local_bin_on_unix() {
        let dirs = SystemBaseDirs;
        let bin_dir = dirs.bin_dir();

        assert!(bin_dir.is_some(), "expected bin_dir to return Some");
        assert!(
            bin_dir
                .as_ref()
                .is_some_and(|p| p.to_string_lossy().contains(".local/bin")),
            "expected path to contain '.local/bin'"
        );
    }
}
