//! Directory resolution abstraction for platform-specific paths.
//!
//! This module provides a trait-based abstraction over directory resolution,
//! enabling dependency injection for testing. The [`BaseDirs`] trait defines
//! the interface for resolving platform-specific directories, while
//! [`SystemBaseDirs`] provides the real implementation using the
//! `directories-next` crate.
//!
//! # Testing
//!
//! In tests, use `MockBaseDirs` (generated by mockall) to avoid writing to
//! the user's actual home directory.

use std::path::PathBuf;

/// Abstraction for resolving platform-specific base directories.
///
/// This trait enables dependency injection for directory resolution,
/// allowing tests to use mock implementations that don't touch the
/// real filesystem.
///
/// # Examples
///
/// ```no_run
/// use whitaker_installer::dirs::{BaseDirs, SystemBaseDirs};
///
/// let dirs = SystemBaseDirs::new().expect("failed to initialise directories");
/// if let Some(bin_dir) = dirs.bin_dir() {
///     println!("Executables go in: {}", bin_dir.display());
/// }
/// ```
#[cfg_attr(test, mockall::automock)]
pub trait BaseDirs {
    /// Returns the user's home directory.
    ///
    /// - Unix: `$HOME` or `/home/<user>`
    /// - Windows: `%USERPROFILE%` or `C:\Users\<user>`
    fn home_dir(&self) -> Option<PathBuf>;

    /// Returns the directory for user executables.
    ///
    /// Returns `~/.local/bin` on all platforms. This follows the XDG Base
    /// Directory Specification convention, providing a consistent location
    /// for user-installed executables across platforms.
    fn bin_dir(&self) -> Option<PathBuf> {
        self.home_dir().map(|h| h.join(".local").join("bin"))
    }

    /// Returns the directory for cloning the Whitaker repository.
    ///
    /// - Linux: `~/.local/share/whitaker`
    /// - macOS: `~/Library/Application Support/whitaker`
    /// - Windows: `%LOCALAPPDATA%\whitaker`
    fn whitaker_data_dir(&self) -> Option<PathBuf>;
}

/// Real implementation of [`BaseDirs`] using the `directories-next` crate.
///
/// This implementation resolves actual platform-specific directories
/// and should be used in production code. It wraps `directories_next::UserDirs`
/// and `directories_next::ProjectDirs` to provide consistent cross-platform
/// directory resolution.
///
/// # Examples
///
/// ```no_run
/// use whitaker_installer::dirs::{BaseDirs, SystemBaseDirs};
///
/// let dirs = SystemBaseDirs::new().expect("failed to initialise directories");
/// let data_dir = dirs.whitaker_data_dir()
///     .expect("could not determine data directory");
/// println!("Whitaker data at: {}", data_dir.display());
/// ```
#[derive(Debug, Clone)]
pub struct SystemBaseDirs {
    user_dirs: directories_next::UserDirs,
    project_dirs: directories_next::ProjectDirs,
}

impl SystemBaseDirs {
    /// Creates a new `SystemBaseDirs` instance.
    ///
    /// Returns `None` if the platform's directory conventions cannot be
    /// determined (e.g., on unsupported platforms or when environment
    /// variables are not set correctly).
    #[must_use]
    pub fn new() -> Option<Self> {
        let user_dirs = directories_next::UserDirs::new()?;
        let project_dirs = directories_next::ProjectDirs::from("", "", "whitaker")?;
        Some(Self {
            user_dirs,
            project_dirs,
        })
    }
}

impl BaseDirs for SystemBaseDirs {
    fn home_dir(&self) -> Option<PathBuf> {
        Some(self.user_dirs.home_dir().to_owned())
    }

    fn whitaker_data_dir(&self) -> Option<PathBuf> {
        Some(self.project_dirs.data_dir().to_owned())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn system_base_dirs_returns_some_on_supported_platforms() {
        let dirs = SystemBaseDirs::new().expect("failed to create SystemBaseDirs");

        assert!(
            dirs.home_dir().is_some(),
            "expected home_dir to return Some"
        );
    }

    #[test]
    fn whitaker_data_dir_contains_whitaker() {
        let dirs = SystemBaseDirs::new().expect("failed to create SystemBaseDirs");
        let data_dir = dirs.whitaker_data_dir();

        assert!(
            data_dir.is_some(),
            "expected whitaker_data_dir to return Some"
        );
        assert!(
            data_dir
                .as_ref()
                .is_some_and(|p| p.to_string_lossy().contains("whitaker")),
            "expected path to contain 'whitaker'"
        );
    }

    #[test]
    fn bin_dir_is_local_bin() {
        let dirs = SystemBaseDirs::new().expect("failed to create SystemBaseDirs");
        let bin_dir = dirs.bin_dir();

        assert!(bin_dir.is_some(), "expected bin_dir to return Some");
        assert!(
            bin_dir
                .as_ref()
                .is_some_and(|p| p.to_string_lossy().contains(".local")),
            "expected path to contain '.local'"
        );
    }
}
