//! Dylint lint crate enforcing that every module begins with an inner doc
//! comment.
//!
//! When the `dylint-driver` feature is enabled this crate exposes the
//! `module_must_have_inner_docs` lint so it can be loaded via Dylint. The lint
//! inspects source modules (`mod foo { .. }` as well as file-backed modules)
//! and emits a warning whenever the body does not start with a `//!` style
//! comment or `#![doc = "..."]` attribute placed before other inner
//! attributes. Inline examples live under `ui/` and cover inline modules,
//! file-backed modules declared with `#[path]`, and macro-generated modules to
//! demonstrate the lint’s behaviour.
//!
//! ```ignore
//! #![warn(module_must_have_inner_docs)]
//!
//! mod documented {
//!     //! Explain the module before adding code.
//!     pub fn value() {}
//! }
//! ```
//!
//! Consumers typically depend on the compiled lint crate and point `dylint`
//! (or `cargo dylint`) at the produced shared library.
#![cfg_attr(feature = "dylint-driver", feature(rustc_private))]

#[cfg(feature = "dylint-driver")]
mod driver;

// The snippet newtypes are parser plumbing shared between the driver's
// submodules through the crate root. They are generated by `base_newtype!`,
// so the underlying struct has no documentable source location either;
// keeping the aliases crate-visible leaves them outwith the public surface.
#[cfg(feature = "dylint-driver")]
pub(crate) use driver::{AttributeBody, MetaList, ParseInput};
// Re-export only the documented lint surface. `impl_late_lint!` also expands
// to the Dylint ABI entry point and lint-pass glue, which have no source
// location that could carry documentation; keeping them out of the public
// path satisfies `missing_docs` without suppressing it. The `no_mangle`
// symbol is still exported from the cdylib for standalone Dylint loading.
#[cfg(feature = "dylint-driver")]
pub use driver::{MODULE_MUST_HAVE_INNER_DOCS, ModuleMustHaveInnerDocs};
