Feature: Module length evaluation
  The module_max_lines lint warns when a module exceeds the configured size.

  Background:
    Given the maximum module length is 5

  Scenario: Module within the configured limit
    Given a module spans 3 lines
    When I evaluate the module length
    Then the module is accepted

  Scenario: Module exceeding the configured limit
    Given a module spans 6 lines
    When I evaluate the module length
    Then the module is rejected

  Scenario: Module exactly at the configured limit
    Given a module spans 5 lines
    When I evaluate the module length
    Then the module is accepted

  Scenario: Module generated by a macro
    Given a module spans 10 lines
    And the module originates from a macro expansion
    When I evaluate the module length
    Then the module evaluation is ignored
